name: Question
description: Ask a usage or design question
title: "[Q] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What you already tried or read
